// Generates src/demo_chip.h: the canned replies of the in-ROM mock chip used by
// `make demo` (DEMO_CHIP). Every reply is produced by the real browser chip
// (web/src/chip/chip.ts) for the attract-mode wallet, so the demo cartridge shows
// exactly what the website shows. Testnet-only BIP-39 test vector, never funded.
//
// usage (from rom/): ../web/node_modules/.bin/tsx assets/gen_demo_chip.mts
import { writeFileSync } from "node:fs";
import { CartChip, demoPersisted, type Persisted } from "../../web/src/chip/chip";
import { walletFromMnemonic } from "../../web/src/chip/keys";
// same resolved files chip.ts loads, so instanceof checks inside the chip hold
// @ts-expect-error untyped deep import
import * as web3 from "../../web/node_modules/@solana/web3.js/lib/index.cjs.js";
// @ts-expect-error untyped deep import
import * as viem from "../../web/node_modules/viem/_esm/index.js";
// @ts-expect-error untyped deep import
import bs58 from "../../web/node_modules/bs58/src/esm/index.js";
// @ts-expect-error untyped deep import
import { wordlist } from "../../web/node_modules/@scure/bip39/wordlists/english.js";

const { Keypair, PublicKey, SystemProgram, Transaction } = web3;
const { parseEther, parseGwei, keccak256 } = viem;

// keep in sync with web/src/landing/attract.ts
const DEMO_WORDS = "legal winner thank year wave sausage worth useful legal winner thank yellow";
const SOL_TO = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM";
const SOL_LAMPORTS = 250_000_000;
const ETH_TO = "0x8ba1f109551bD432803012645Ac136ddd64DBA72";
const ETH_VALUE = parseEther("0.01");
const ETH_MAX_FEE_PER_GAS = parseGwei("2");

let stored: Persisted | null = demoPersisted(DEMO_WORDS, [0, 0, 0, 0]);
const chip = new CartChip({ load: () => stored, save: (p) => (stored = p), clear: () => (stored = null) });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const handle = (cmd: number, arg = 0, data = new Uint8Array()) => (chip as any).handle(cmd, arg, data) as { status: number; data?: Uint8Array | string };
const bytes = (d: Uint8Array | string | undefined) => (typeof d === "string" ? Uint8Array.from(d, (c) => c.charCodeAt(0)) : (d ?? new Uint8Array()));

if (handle(0x05, 0, Uint8Array.from([0, 0, 0, 0])).status !== 0) throw new Error("unlock failed");
chip.setBalance("sol", 2_480_000_000n);
chip.setBalance("evm", 420_000_000_000_000_000n);
const addr = chip.addresses!;

const account = [0, 1].map((c) => bytes(handle(0x06, c).data));
const qr = [0, 1].map((c) => bytes(handle(0x0c, c).data));

// the two sign requests, decoded by the real chip
const wallet = walletFromMnemonic(DEMO_WORDS);
const from = new PublicKey(addr.sol);
const solTx = new Transaction({ feePayer: from, recentBlockhash: "EETubP5AKHgjPAhzPAFcb8BAY1hMH639CWCFTqi3hq1k" }).add(
  SystemProgram.transfer({ fromPubkey: from, toPubkey: new PublicKey(SOL_TO), lamports: SOL_LAMPORTS }),
);
chip.requestSignature({ chain: "sol", tx: solTx });
const solPending = bytes(handle(0x07).data);
handle(0x08, 0); // reject, to make room for the next one
const ethTx = { chainId: 11155111, to: ETH_TO, value: ETH_VALUE, nonce: 3, gas: 21000n, maxFeePerGas: ETH_MAX_FEE_PER_GAS, maxPriorityFeePerGas: parseGwei("1"), type: "eip1559" } as const;
chip.requestSignature({ chain: "evm", tx: ethTx });
const ethPending = bytes(handle(0x07).data);
handle(0x08, 0);

// what the phone would report after broadcasting: real signatures of these transactions
solTx.sign(Keypair.fromSecretKey(wallet.sol.secretKey));
const solSig: string = bs58.encode(solTx.signature!);
const ethHash: string = keccak256(await wallet.evm.signTransaction(ethTx));
const short = (h: string) => `${h.slice(0, 8)}..${h.slice(-8)}`;

// restore: the distinct words of the demo phrase, with their BIP-39 indices
const words = [...new Set(DEMO_WORDS.split(" "))].sort();
const phraseIdx = DEMO_WORDS.split(" ").map((w) => wordlist.indexOf(w));

const arr = (name: string, b: Uint8Array) =>
  `static const uint8_t ${name}[${b.length}] = {\n${Array.from(b, (x) => "0x" + x.toString(16).padStart(2, "0"))
    .join(",")
    .replace(/((?:0x..,){16})/g, "$1\n")}\n};\n`;
const str = (s: string) => JSON.stringify(s);

let h = `/* Generated by assets/gen_demo_chip.mts. Do not edit. Only used by \`make demo\`. */
/* SOL ${addr.sol} */
/* EVM ${addr.evm} */
#define DEMO_MNEMONIC ${str(DEMO_WORDS)}
#define DEMO_SOL_HASH ${str(short(solSig))}
#define DEMO_EVM_HASH ${str(short(ethHash))}
`;
h += arr("demo_account_sol", account[0]);
h += arr("demo_account_evm", account[1]);
h += arr("demo_qr_sol", qr[0]);
h += arr("demo_qr_evm", qr[1]);
h += arr("demo_pending_sol", solPending);
h += arr("demo_pending_evm", ethPending);
h += arr("demo_phrase_idx", Uint8Array.from(phraseIdx.flatMap((i) => [i >> 8, i & 0xff])));
h += `#define DEMO_WORD_COUNT ${words.length}\n`;
h += `static const char *const demo_words[DEMO_WORD_COUNT] = {${words.map(str).join(", ")}};\n`;
h += `static const uint16_t demo_word_idx[DEMO_WORD_COUNT] = {${words.map((w) => wordlist.indexOf(w)).join(", ")}};\n`;

writeFileSync(new URL("../src/demo_chip.h", import.meta.url), h);
console.log("wrote src/demo_chip.h", addr, short(solSig), short(ethHash));
