"""
Builds every graphic the ROM uses and writes rom/src/assets.c + assets.h.

DMG has 4 shades: 0 = lightest (paper), 1 = light grey, 2 = dark grey, 3 = ink.
Tiles are 8x8, 2 bits per pixel. Background and sprites share the 256 tiles at
0x8000 (GBDK's default LCDC), so the budget is laid out like this:

    0..95     font, ink on paper            (ASCII 32..127)
    96..154   font, grey on paper           (ASCII 32..90: captions, uppercase)
              (the boot screen reuses this range for the big logo)
    155..239  UI: frames, icons, button glyphs, bars, big digits
    240..255  QR code 2x2 blocks (drawn by the ROM itself)

Run:  python3 rom/assets/gen_assets.py   (the Makefile does this)
"""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).parent
SRC = HERE.parent / "src"
FONT = ImageFont.truetype(str(HERE / "fonts" / "PixelOperatorMono8.ttf"), 8)
FONT_BIG = ImageFont.truetype(str(HERE / "fonts" / "PixelOperator-Bold.ttf"), 16)

FONT_INK = 0
FONT_GREY = 96
UI = 155
QR = 240


def glyph(ch: str, font=FONT, size=(8, 8), offset=(0, 0)) -> list[list[int]]:
    im = Image.new("L", size, 0)
    ImageDraw.Draw(im).text(offset, ch, font=font, fill=255)
    return [[1 if im.getpixel((x, y)) > 127 else 0 for x in range(size[0])] for y in range(size[1])]


def encode(px: list[list[int]]) -> list[int]:
    """8x8 grid of shades (0..3) -> 16 bytes of 2bpp tile data."""
    out = []
    for row in px:
        lo = hi = 0
        for x, v in enumerate(row):
            lo |= (v & 1) << (7 - x)
            hi |= ((v >> 1) & 1) << (7 - x)
        out += [lo, hi]
    return out


def shade(mask, on, off=0):
    return [[on if v else off for v in row] for row in mask]


def art(s: str) -> list[list[int]]:
    """ASCII pixel art: '.'=0 ':'=1 '+'=2 '#'=3."""
    m = {".": 0, ":": 1, "+": 2, "#": 3}
    rows = [r for r in s.strip("\n").split("\n")]
    return [[m[c] for c in r.strip()] for r in rows]


def split(px, w_tiles, h_tiles):
    """Cut a (w*8)x(h*8) picture into tiles, row-major."""
    tiles = []
    for ty in range(h_tiles):
        for tx in range(w_tiles):
            tiles.append([row[tx * 8:(tx + 1) * 8] for row in px[ty * 8:(ty + 1) * 8]])
    return tiles


# ---------------------------------------------------------------- UI tiles

ui: list[tuple[str, list[list[int]]]] = []


def add(name, px):
    ui.append((name, px))


# rounded card frame (2px corner radius, 1px grey line)
add("FRAME_TL", art("""
........
........
...+++++
..+.....
..+.....
..+.....
..+.....
..+.....
"""))
add("FRAME_T", art("""
........
........
++++++++
........
........
........
........
........
"""))
add("FRAME_TR", art("""
........
........
+++++...
.....+..
.....+..
.....+..
.....+..
.....+..
"""))
add("FRAME_L", art("\n".join(["..+....."] * 8)))
add("FRAME_R", art("\n".join([".....+.."] * 8)))
add("FRAME_BL", art("""
..+.....
..+.....
..+.....
..+.....
...+++++
........
........
........
"""))
add("FRAME_B", art("""
........
........
........
........
++++++++
........
........
........
"""))
add("FRAME_BR", art("""
.....+..
.....+..
.....+..
.....+..
+++++...
........
........
........
"""))
# hairline divider
add("RULE", art("""
........
........
........
........
::::::::
........
........
........
"""))

# button glyphs: filled dark circle with a light letter
add("BTN_A", art("""
..####..
.######.
###..###
##.##.##
##....##
##.##.##
.######.
..####..
"""))
add("BTN_B", art("""
..####..
.######.
##...###
##.##.##
##...###
##.##.##
.##...#.
..####..
"""))
add("BTN_SEL_L", art("""
........
..######
.#######
.##..#..
.###.#.#
.#..##..
.#######
..######
"""))
add("BTN_SEL_R", art("""
........
######..
#######.
#..#.##.
#.##.##.
#..#..#.
#######.
######..
"""))

# 16x16 icons as 2x2 tiles: key, solana, ether, shield, lock, check, phone, chip
ICONS = {
    "KEY": """
................
.....######.....
....#++++++#....
...#+#....#+#...
...#+#....#+#...
...#+#....#+#...
....#++++++#....
.....##++##.....
.......#+#......
.......#+#......
.......#+###....
.......#+++#....
.......#+###....
.......#+++#....
.......#####....
................
""",
    "SOL": """
................
................
....##########..
...##########...
..##########....
................
................
..##########....
...##########...
....##########..
................
................
....##########..
...##########...
..##########....
................
""",
    "ETH": """
.......##.......
......####......
......#++#......
.....#++++#.....
.....#++++#.....
....#++++++#....
....#++++++#....
...##++++++##...
...#########....
....#++++++#....
.....#++++#.....
.....#++++#.....
......#++#......
......#++#......
.......##.......
................
""",
    "SHIELD": """
................
.......##.......
.....##++##.....
...##++++++##...
..#++++++++++#..
..#+++++++++#+..
..#++++++++##+..
..#+++#++###++..
..#++###+##+++..
..#+++####++++..
...#+++##++++#..
...#+++++++++#..
....#+++++++#...
.....##+++##....
.......###......
................
""",
    "LOCK": """
................
......####......
.....#....#.....
....#......#....
....#......#....
....#......#....
...##########...
...#++++++++#...
...#++++++++#...
...#+++##+++#...
...#+++##+++#...
...#++++++++#...
...#++++++++#...
...##########...
................
................
""",
    "CHECK": """
................
.....######.....
...##......##...
..#..........#..
.#..........#.#.
.#.........#..#.
#.........#....#
#..#.....#.....#
#...#...#......#
#....#.#.......#
.#....#.......#.
.#............#.
..#..........#..
...##......##...
.....######.....
................
""",
    "PHONE": """
................
....########....
...#........#...
...#.######.#...
...#.#::::#.#...
...#.#::::#.#...
...#.#::::#.#...
...#.#::::#.#...
...#.#::::#.#...
...#.#::::#.#...
...#.######.#...
...#........#...
...#...##...#...
...#........#...
....########....
................
""",
    "SHAKE": """
................
.#..........#...
#...######...#..
#..#++++++#..#..
...#+::::+#.....
...#+::::+#.....
...#+::::+#.....
...#++++++#.....
...#+#++#+#.....
...#++++##+.....
...#+++++++#....
...#+++++++#....
#...#######..#..
#............#..
.#..........#...
................
""",
}
for name, a in ICONS.items():
    for i, t in enumerate(split(art(a), 2, 2)):
        add(f"ICON_{name}_{i}", t)

# smooth bar: 9 fill levels (0..8 px) for a 1-tile-tall rounded track
for n in range(9):
    rows = []
    for y in range(8):
        if y in (2, 5):
            rows.append([2] * 8)  # track outline
        elif y in (3, 4):
            rows.append([3 if x < n else 0 for x in range(8)])
        else:
            rows.append([0] * 8)
    add(f"BAR_{n}", rows)
add("BAR_CAP_L", art("""
........
........
......++
.....+..
.....+..
......++
........
........
"""))
add("BAR_CAP_R", art("""
........
........
++......
..+.....
..+.....
++......
........
........
"""))

# cursor arrow (used as a sprite)
add("CURSOR", art("""
........
.##.....
.###....
.####...
.#####..
.####...
.###....
.##.....
"""))
add("DOT", art("""
........
........
...##...
..####..
..####..
...##...
........
........
"""))
add("SOLID1", [[1] * 8 for _ in range(8)])

# big digits: 0-9, '.', ' ' drawn with the 16px bold face, 1 tile wide x 2 tall
BIG = "0123456789. "
big_tiles = []
for ch in BIG:
    m = glyph(ch, FONT_BIG, (8, 16), (0, -1))  # glyphs span rows 4..13 at offset 0; center them
    px = shade(m, 3)
    big_tiles += split(px, 1, 2)
for i, t in enumerate(big_tiles):
    add(f"BIG_{i}", t)

assert len(ui) <= QR - UI, f"UI tiles overflow: {len(ui)} > {QR - UI}"


# ---------------------------------------------------------------- network icons
# The home screen's EVM card shows one network at a time, so these live in ROM and get copied into
# the ICON_ETH tiles when the card is drawn (VRAM has no room for all five). Order = ROM's net_icon().

def disc(fn):
    """16x16 picture from fn(x, y) -> shade, sampled at pixel centres."""
    return [[fn(x + 0.5, y + 0.5) for x in range(16)] for y in range(16)]


def base_icon(x, y):
    # a solid coin with a bar cut in from the left, like Base's mark
    if (x - 8) ** 2 + (y - 8) ** 2 > 7.2 ** 2:
        return 0
    return 0 if 7 <= y <= 9 and x < 10 else 3


NET_ICONS = {
    "ETH": art(ICONS["ETH"]),
    "BASE": disc(base_icon),
    "ARB": art("""
................
......####......
....##....##....
..##........##..
..#....##....#..
..#...#++#...#..
..#...#++#...#..
..#..#+..+#..#..
..#..#+..+#..#..
..#.#+....+#.#..
..#.#+....+#.#..
..##........##..
....##....##....
......####......
................
................
"""),
    "HYPE": art("""
................
.....######.....
...##......##...
..#..........#..
.#..##....##..#.
.#..##....##..#.
#...##....##...#
#...########...#
#...########...#
#...##....##...#
.#..##....##..#.
.#..##....##..#.
..#..........#..
...##......##...
.....######.....
................
"""),
    "HOOD": art("""
................
............###.
..........##++#.
.........#+++#..
........#+++#...
.......#+++#....
......#+++#.....
.....#+++#......
....#+++#.......
....#++#........
...#++#.........
...###..........
..#.............
.#..............
#...............
................
"""),
}
for name, px in NET_ICONS.items():
    assert len(px) == 16 and all(len(r) == 16 for r in px), name
net_icon_tiles = [t for px in NET_ICONS.values() for t in split(px, 2, 2)]

# ---------------------------------------------------------------- logo (boot only)
# Pixel-doubled wordmark plus a doubled key, loaded over the grey font on the boot screen.

def double(px):
    out = []
    for row in px:
        r = [v for v in row for _ in (0, 1)]
        out += [r, list(r)]
    return out

word = "kagiboy"
wm = Image.new("L", (56, 16), 0)
wd = ImageDraw.Draw(wm)
wd.text((round((56 - wd.textlength(word, font=FONT_BIG)) / 2), -3), word, font=FONT_BIG, fill=255)
word_px = double([[3 if wm.getpixel((x, y)) > 127 else 0 for x in range(56)] for y in range(12)])  # 112x24
LOGO_W, LOGO_H = 14, 3
logo_tiles = split(word_px, LOGO_W, LOGO_H)
KEY_W = KEY_H = 4
key_tiles = split(double(art(ICONS["KEY"])), KEY_W, KEY_H)
logo_tiles += key_tiles
assert len(logo_tiles) <= UI - FONT_GREY, f"logo {len(logo_tiles)} > {UI - FONT_GREY}"

# ---------------------------------------------------------------- write C


def c_array(name, tiles):
    data = [b for t in tiles for b in encode(t)]
    lines = [", ".join(f"0x{b:02X}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    return f"const uint8_t {name}[] = {{\n    " + ",\n    ".join(lines) + "\n};\n"


font_ink = [shade(glyph(chr(c)), 3) for c in range(32, 128)]
font_grey = [shade(glyph(chr(c)), 2) for c in range(32, 91)]

c = ['/* generated by rom/assets/gen_assets.py; do not edit */', '#include <stdint.h>', '#include "assets.h"', ""]
c.append(c_array("font_ink_tiles", font_ink))
c.append(c_array("font_grey_tiles", font_grey))
c.append(c_array("ui_tiles", [t for _, t in ui]))
c.append(c_array("logo_tiles", logo_tiles))
c.append(c_array("net_icon_tiles", net_icon_tiles))
(SRC / "assets.c").write_text("\n".join(c))

h = [
    "/* generated by rom/assets/gen_assets.py; do not edit */",
    "#ifndef ASSETS_H",
    "#define ASSETS_H",
    "#include <stdint.h>",
    "",
    f"#define T_FONT_INK {FONT_INK}",
    f"#define T_FONT_GREY {FONT_GREY}",
    f"#define T_UI {UI}",
    f"#define T_QR {QR}",
    f"#define N_FONT_INK {len(font_ink)}",
    f"#define N_FONT_GREY {len(font_grey)}",
    f"#define N_UI {len(ui)}",
    f"#define N_LOGO {len(logo_tiles)}",
    f"#define LOGO_W {LOGO_W}",
    f"#define LOGO_H {LOGO_H}",
    f"#define KEY_W {KEY_W}",
    f"#define KEY_H {KEY_H}",
    f"#define LOGO_KEY_FIRST {LOGO_W * LOGO_H}",
    "",
]
for i, (name, _) in enumerate(ui):
    h.append(f"#define T_{name} {UI + i}")
h += [
    "",
    "extern const uint8_t font_ink_tiles[];",
    "extern const uint8_t font_grey_tiles[];",
    "extern const uint8_t ui_tiles[];",
    "extern const uint8_t logo_tiles[];",
    "extern const uint8_t net_icon_tiles[]; /* 5 icons x 4 tiles: ETH, BASE, ARB, HYPE, HOOD */",
    "",
    "#endif",
    "",
]
(SRC / "assets.h").write_text("\n".join(h))

# preview atlas for humans
atlas_tiles = font_ink + font_grey + [t for _, t in ui] + logo_tiles
cols = 16
rows = (len(atlas_tiles) + cols - 1) // cols
pal = [(224, 248, 208), (136, 192, 112), (52, 104, 86), (8, 24, 32)]
img = Image.new("RGB", (cols * 9, rows * 9), (255, 255, 255))
for i, t in enumerate(atlas_tiles):
    ox, oy = (i % cols) * 9, (i // cols) * 9
    for y in range(8):
        for x in range(8):
            img.putpixel((ox + x, oy + y), pal[t[y][x]])
img.resize((img.width * 4, img.height * 4), Image.NEAREST).save(HERE / "atlas-preview.png")
print(f"font {len(font_ink)}+{len(font_grey)}, ui {len(ui)}/{QR - UI}, logo {len(logo_tiles)}")

# assembled previews (logo, big digits) for humans
prev = Image.new("RGB", (LOGO_W * 8, LOGO_H * 8 + 20), pal[0])
logo_tiles = logo_tiles[: LOGO_W * LOGO_H]  # preview the wordmark only
for i, t in enumerate(logo_tiles):
    ox, oy = (i % LOGO_W) * 8, (i // LOGO_W) * 8
    for y in range(8):
        for x in range(8):
            prev.putpixel((ox + x, oy + y), pal[t[y][x]])
for i, ch in enumerate("0123456789."):
    top, bot = big_tiles[i * 2], big_tiles[i * 2 + 1]
    for y in range(16):
        for x in range(8):
            v = (top if y < 8 else bot)[y % 8][x]
            if i * 8 + x < prev.width:
                prev.putpixel((i * 8 + x, LOGO_H * 8 + 2 + y), pal[v])
prev.resize((prev.width * 6, prev.height * 6), Image.NEAREST).save(HERE / "logo-preview.png")
