"""Fetch real token and chain logos from Trust Wallet's open assets repo into public/tokens/.

usage: ./node_modules/.bin/tsx scripts/token-list.ts > /tmp/tokens.json
       python3 scripts/fetch_token_icons.py /tmp/tokens.json
Writes 64 px WebP files and src/app/tokenIcons.ts (lookup by chain:address, then by symbol).
"""
import io, json, os, sys, urllib.request
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "public", "tokens")
TS = os.path.join(HERE, "..", "src", "app", "tokenIcons.ts")
RAW = "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains"
TW = {"solana": "solana", "ethereum": "ethereum", "0x2105.base": "base", "0xa4b1.arbitrum": "arbitrum", "hyper": "hyperevm", "robinhood": None}
NATIVE = {"11111111111111111111111111111111", "0x0000000000000000000000000000000000000000"}


def keccak_checksum(addr):
    # EIP-55 via node (viem is already installed), batched below
    return addr


def get(url):
    try:
        with urllib.request.urlopen(url, timeout=20) as r:
            return r.read()
    except Exception:
        return None


def save(data, name):
    im = Image.open(io.BytesIO(data)).convert("RGBA").resize((64, 64), Image.LANCZOS)
    im.save(os.path.join(OUT, name), "WEBP", quality=90)


def main():
    tokens = json.load(open(sys.argv[1]))
    os.makedirs(OUT, exist_ok=True)
    # checksum every EVM address in one node call
    evm = [t["address"] for t in tokens if t["address"].startswith("0x")]
    import subprocess
    sums = json.loads(subprocess.check_output(
        ["node", "-e", "const {getAddress}=require('viem');console.log(JSON.stringify(JSON.parse(process.argv[1]).map(a=>getAddress(a))))", json.dumps(evm)],
        cwd=os.path.join(HERE, "..")))
    cs = dict(zip(evm, sums))
    icons, by_symbol, chains = {}, {}, {}
    for key, tw in TW.items():
        if tw and (d := get(f"{RAW}/{tw}/info/logo.png")):
            save(d, f"chain-{tw}.webp")
            chains[key] = f"/tokens/chain-{tw}.webp"
    for t in tokens:
        tw = TW[t["chain"]]
        addr = t["address"]
        name = f"{t['chain'].replace('.', '-')}-{addr.lower()}.webp"
        data = None
        if tw:
            if addr in NATIVE:
                data = get(f"{RAW}/{tw}/info/logo.png")
            else:
                data = get(f"{RAW}/{tw}/assets/{cs.get(addr, addr)}/logo.png")
        if data:
            save(data, name)
            path = f"/tokens/{name}"
            icons[f"{t['chain']}:{addr.lower()}"] = path
            by_symbol.setdefault(t["symbol"].upper(), path)
        print(("ok  " if data else "--  ") + t["chain"], t["symbol"])
    lines = ["// generated by scripts/fetch_token_icons.py (logos: github.com/trustwallet/assets)", ""]
    lines.append("export const TOKEN_ICONS: Record<string, string> = " + json.dumps(icons, indent=2) + ";")
    lines.append("")
    lines.append("/** the same coin's logo from another chain, for tokens Trust Wallet doesn't list on this one */")
    lines.append("export const SYMBOL_ICONS: Record<string, string> = " + json.dumps(by_symbol, indent=2) + ";")
    lines.append("")
    lines.append("export const CHAIN_ICONS: Record<string, string> = " + json.dumps({**chains, "robinhood": "/tokens/chain-robinhood.svg"}, indent=2) + ";")
    open(TS, "w").write("\n".join(lines) + "\n")


main()
