/* generated by rom/assets/gen_assets.py; do not edit */
#ifndef ASSETS_H
#define ASSETS_H
#include <stdint.h>

#define T_FONT_INK 0
#define T_FONT_GREY 96
#define T_UI 155
#define T_QR 240
#define N_FONT_INK 96
#define N_FONT_GREY 59
#define N_UI 83
#define N_LOGO 58
#define LOGO_W 14
#define LOGO_H 3
#define KEY_W 4
#define KEY_H 4
#define LOGO_KEY_FIRST 42

#define T_FRAME_TL 155
#define T_FRAME_T 156
#define T_FRAME_TR 157
#define T_FRAME_L 158
#define T_FRAME_R 159
#define T_FRAME_BL 160
#define T_FRAME_B 161
#define T_FRAME_BR 162
#define T_RULE 163
#define T_BTN_A 164
#define T_BTN_B 165
#define T_BTN_SEL_L 166
#define T_BTN_SEL_R 167
#define T_ICON_KEY_0 168
#define T_ICON_KEY_1 169
#define T_ICON_KEY_2 170
#define T_ICON_KEY_3 171
#define T_ICON_SOL_0 172
#define T_ICON_SOL_1 173
#define T_ICON_SOL_2 174
#define T_ICON_SOL_3 175
#define T_ICON_ETH_0 176
#define T_ICON_ETH_1 177
#define T_ICON_ETH_2 178
#define T_ICON_ETH_3 179
#define T_ICON_SHIELD_0 180
#define T_ICON_SHIELD_1 181
#define T_ICON_SHIELD_2 182
#define T_ICON_SHIELD_3 183
#define T_ICON_LOCK_0 184
#define T_ICON_LOCK_1 185
#define T_ICON_LOCK_2 186
#define T_ICON_LOCK_3 187
#define T_ICON_CHECK_0 188
#define T_ICON_CHECK_1 189
#define T_ICON_CHECK_2 190
#define T_ICON_CHECK_3 191
#define T_ICON_PHONE_0 192
#define T_ICON_PHONE_1 193
#define T_ICON_PHONE_2 194
#define T_ICON_PHONE_3 195
#define T_ICON_SHAKE_0 196
#define T_ICON_SHAKE_1 197
#define T_ICON_SHAKE_2 198
#define T_ICON_SHAKE_3 199
#define T_BAR_0 200
#define T_BAR_1 201
#define T_BAR_2 202
#define T_BAR_3 203
#define T_BAR_4 204
#define T_BAR_5 205
#define T_BAR_6 206
#define T_BAR_7 207
#define T_BAR_8 208
#define T_BAR_CAP_L 209
#define T_BAR_CAP_R 210
#define T_CURSOR 211
#define T_DOT 212
#define T_SOLID1 213
#define T_BIG_0 214
#define T_BIG_1 215
#define T_BIG_2 216
#define T_BIG_3 217
#define T_BIG_4 218
#define T_BIG_5 219
#define T_BIG_6 220
#define T_BIG_7 221
#define T_BIG_8 222
#define T_BIG_9 223
#define T_BIG_10 224
#define T_BIG_11 225
#define T_BIG_12 226
#define T_BIG_13 227
#define T_BIG_14 228
#define T_BIG_15 229
#define T_BIG_16 230
#define T_BIG_17 231
#define T_BIG_18 232
#define T_BIG_19 233
#define T_BIG_20 234
#define T_BIG_21 235
#define T_BIG_22 236
#define T_BIG_23 237

extern const uint8_t font_ink_tiles[];
extern const uint8_t font_grey_tiles[];
extern const uint8_t ui_tiles[];
extern const uint8_t logo_tiles[];

#endif
