// Writes rom/src/brand.h from brand.json so the ROM and the website share one name.
import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("..", import.meta.url);
const brand = JSON.parse(readFileSync(new URL("brand.json", root)));
const name = brand.name.toUpperCase();
if (name.length > 20) throw new Error("brand name must fit the 20-column Game Boy screen");
writeFileSync(
  new URL("rom/src/brand.h", root),
  `/* generated by scripts/gen-brand.mjs from brand.json; do not edit */\n#define BRAND_NAME "${name}"\n#define BRAND_NAME_LEN ${name.length}\n`
);
console.log(`brand.h -> ${name}`);
